Update Dockerfile

diff --git a/games/source/Dockerfile b/games/source/Dockerfile
--- a/games/source/Dockerfile
+++ b/games/source/Dockerfile
@@ -8,10 +8,15 @@ ENV DEBIAN_FRONTEND=noninteractive
 
 RUN dpkg --add-architecture i386 \
     && apt update \
-    && apt upgrade -y \
-    && apt install -y tar curl gcc g++ lib32gcc-s1 libgcc1 libcurl4-gnutls-dev:i386 libssl1.1:i386 libcurl4:i386 lib32tinfo6 libtinfo6:i386 lib32z1 lib32stdc++6 libncurses5:i386 libcurl3-gnutls:i386 libsdl2-2.0-0:i386 iproute2 gdb libsdl1.2debian libfontconfig1 telnet net-tools netcat tzdata \
-    || { echo "APT INSTALL FAILED"; apt-get clean; exit 1; } \
-    && useradd -m -d /home/container container
+    && apt upgrade -y
+
+RUN apt install -y tar curl gcc g++ lib32gcc-s1 libgcc1 \
+    && apt install -y libcurl4-gnutls-dev:i386 libssl1.1:i386 libcurl4:i386 \
+    && apt install -y lib32tinfo6 libtinfo6:i386 lib32z1 lib32stdc++6 libncurses5:i386 \
+    && apt install -y libcurl3-gnutls:i386 libsdl2-2.0-0:i386 \
+    && apt install -y iproute2 gdb libsdl1.2debian libfontconfig1 telnet net-tools netcat tzdata \
+    && useradd -m -d /home/container container \
+    || { echo "APT INSTALL FAILED"; apt-get clean; exit 1; }
 
 USER container
 ENV USER=container HOME=/home/container
